version: 2.1

jobs:
  lint-app:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
  build-docker:
    machine: true
    steps:
      - checkout
      - run:
          name: building
          command: |
            curl -fsSl https://deb.nodesource.com/setup_16.x | sudo -E bash -
            sudo apt-get install -y nodejs
            node -v
            npm -v
            source set_env.sh

            # Build
            echo '-----building----- !!'
            docker build -t udagram-api-feed:v2 ./udagram-api-feed
            docker build -t udagram-api-user:v2 ./udagram-api-user
            docker build -t udagram-frontend:v2 ./udagram-frontend
            docker build -t reverseproxy:v2 ./udagram-reverseproxy

            # Tag
            echo '-----tagging----- !'
            docker tag udagram-api-feed:v2 khoinm260199/udagram-api-feed:v2
            docker tag udagram-api-user:v2 khoinm260199/udagram-api-user:v2
            docker tag udagram-frontend:v2 khoinm260199/udagram-frontend:v2
            docker tag reverseproxy:v2 khoinm260199/reverseproxy:v2

            echo '---List image created---'
            docker image ls

      - run:
          name: push-to-dockerhub
          command: |
            # Login dockerhub
            echo '__Login DockerHub__'
            docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
            # Pushing
            echo '__Pushing images__'
            docker push khoinm260199/udagram-api-feed:v2
            docker push khoinm260199/udagram-api-user:v2
            docker push khoinm260199/udagram-frontend:v2
            docker push khoinm260199/reverseproxy:v2

workflows:
  default:
    jobs:
      - lint-app
      - build-docker:
          requires: [lint-app]
    