name: Docker Image CI

on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run:
        name: building
        command: |
          curl -fsSl https://deb.nodesource.com/setup_16.x | sudo -E bash -
          sudo apt-get install -y nodejs
          node -v
          npm -v

          # Build
          echo '-----building----- !!'
          docker build -t udagram-api-feed:v1 ./udagram-api-feed
          docker build -t udagram-api-user:v1 ./udagram-api-user
          docker build -t udagram-frontend:v1 ./udagram-frontend
          docker build -t reverseproxy:v1 ./udagram-reverseproxy

          # Tag
          echo '-----tagging----- !'
          docker tag udagram-api-feed:v1 khoinm260199/udagram-api-feed:v3
          docker tag udagram-api-user:v1 khoinm260199/udagram-api-user:v3
          docker tag udagram-frontend:v1 khoinm260199/udagram-frontend:v3
          docker tag reverseproxy:v1 khoinm260199/reverseproxy:v3

          echo '---List image created---'
          docker image ls

    - run:
        name: push-to-dockerhub
        command: |
          # Login dockerhub
          echo '__Login DockerHub__'
          docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
          # Pushing
          echo '__Pushing images__'
          docker push khoinm260199/udagram-api-feed:v3
          docker push khoinm260199/udagram-api-user:v3
          docker push khoinm260199/udagram-frontend:v3
          docker push khoinm260199/reverseproxy:v3

