name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Node.js
      run: |
        curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
        sudo apt-get install -y nodejs
        node -v
        npm -v

    - name: Build and Tag Docker Images
      run: |
        # Build
        echo '-----building----- !!'
        docker build -t udagram-api-feed:v1 ./udagram-api-feed
        docker build -t udagram-api-user:v1 ./udagram-api-user
        docker build -t udagram-frontend:v1 ./udagram-frontend
        docker build -t reverseproxy:v1 ./udagram-reverseproxy

        # Tag
        echo '-----tagging----- !'
        docker tag udagram-api-feed:v1 khoinm260199/udagram-api-feed:v3
        docker tag udagram-api-user:v1 khoinm260199/udagram-api-user:v3
        docker tag udagram-frontend:v1 khoinm260199/udagram-frontend:v3
        docker tag reverseproxy:v1 khoinm260199/reverseproxy:v3

        echo '---List image created---'
        docker image ls

    - name: Login to DockerHub and Push Images
      run: |
        echo '__Login DockerHub__'
        docker login -u="${{ secrets.DOCKERHUB_USERNAME }}" -p="${{ secrets.DOCKERHUB_PASSWORD }}"
        echo '__Pushing images__'
        docker push khoinm260199/udagram-api-feed:v3
        docker push khoinm260199/udagram-api-user:v3
        docker push khoinm260199/udagram-frontend:v3
        docker push khoinm260199/reverseproxy:v3
